//! §35 compatibility entry: a build script, which is plain Rust and stays plain Rust (§4.6). It
//! writes a table into `OUT_DIR`, and the Uredo source includes it with `include!` inside a
//! `rust { }` block, since an `include!` in item position is Rust's own mechanism.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out).join("table.rs");
    let mut body = String::from("/// Generated by build.rs at compile time.\npub const SQUARES: [u32; 8] = [");
    for i in 0u32..8 {
        body.push_str(&format!("{}, ", i * i));
    }
    body.push_str("];\n");
    fs::write(&dest, body).expect("write the generated table");
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rustc-env=COMPAT_BUILD_STAMP=generated");
}
